name: Publish release artifact

on:
  release:
    types: [created]

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Copy build-artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.nvim_github_action }}
      with:
        args: "./dist/*.tar.gz"
