name: Deploy release

on:
  release:
    types: [published, created]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repo
        if: github.ref == 'refs/heads/releases'
        uses: actions/checkout@v2

      - name: Bump version and push tag
        if: github.ref == 'refs/heads/releases' || github.event.pull_request.base.ref == 'main'
        uses: anothrNick/github-tag-action@master
        env:
          ## PAT generated on Github, added to repo as secret
          GITHUB_TOKEN: ${{ secrets.NVIM_GITHUB_TOKEN }}
          REPO_OWNER: redjax
          WITH_V: true
          RELEASE_BRANCHES: release
          DEFAULT_BRAND: release
